### ISSUE TITLE
Client: Create a test structure

### ISSUE THREAD

**Issue by Brisbin** [jcrrad/Chess#10]
We need to create a file structure to support JUnit tests that allow us to write tests for all of our logic and classes. The structure will be identical to the structure of the main classes but in a separate source folder called test.

**Comment by scantwell** [comment]
Should this be R & D? I am not sure where it should be any comments? 0.1?

**Comment by Brisbin** [comment]
Do we want to create an actual like coding/development milestone? Is that what 1.0 is?

**Comment by scantwell** [comment]
This was not intended to be closed, sorry for the mistake. The 0.1 is the coding milestone, so anything that has to do with code I'd say put there. I am open for any kind of formating changes since we are at a very early stage.

**Comment by Brisbin** [comment]
I created the base test structure that i think we should follow. Another tool that we should get is MoreUnit, it assists with writing JUnit tests and is a useful tool. I put a link to the homepage in the Open Discussion for Code Standards
