### ISSUE TITLE
Server: Client-to-Server Connections

### ISSUE THREAD

**Issue by scantwell** [jcrrad/Chess#2]
Find an effective way to communicate from server to client, client to server, and multiple clients to server. Create one or more prototypes demonstrating your findings.

**Comment by scantwell** [comment]
Find an effective way to communicate from server to client, client to server, and multiple clients to server. Create one or more prototypes demonstrating your findings.

**Comment by ZerOmNia** [comment]
So far were leaning toward a "Fat Client" model for the Client-to-Server connection.
The clients will handle all the game logic for chess, and the server is responsible for controlling the lobby, chat, player data, and setting up a connection for  a game.

**Comment by scantwell** [comment]
To give us more insight on how exactly TCP works with sockets and ports.

TCP Protocol docs: https://www.ietf.org/rfc/rfc793.txt

**Comment by scantwell** [comment]
The R&D phase is over for this. No longer relevant so I am closing.
