### ISSUE TITLE
Create Logic for Controllers

### ISSUE THREAD

**Issue by Brisbin** [jcrrad/Chess#27]
The controllers need their logic to handle calling to the model and manipulating the view. Some model methods will have to be somewhat mocked as the server is not 100% complete, but it shouldn't stop us from adding the logic and testing it with some simple methods to ensure correctness. Then when the server is complete it should be relatively plug and play.

**Comment by scantwell** [comment]
All server implementations have been accomplished, controllers now run the GUI seamlessly. The design is based off of state changes with a observer/observed pattern.
