### ISSUE TITLE
CheckMate

### ISSUE THREAD

**Issue by jcrrad** [jcrrad/Chess#32]
Checkmate needs to be implemented and verified to be working correctly

**Comment by jcrrad** [comment]
Checkmate has partially been tested and verified to work correctly still minor issue that need to be cleared up

**Comment by scantwell** [comment]
When moving king into a position where he is vulnerable, the only move that can be made is to move the King out of that position. This should be fixed so that you still can move any other piece.

**Comment by scantwell** [comment]
This has been corrected, the issues stemmed from some refactoring that had been done.
