### ISSUE TITLE
Find a static code analysis tool

### ISSUE THREAD

**Issue by scantwell** [jcrrad/Chess#8]
Maybe Coverity is a solution, there are tons for java with a quick java search, lets find a good one!

**Comment by jcrrad** [comment]
Since we are all familiar with it from last semester I think we should use coverity. It works well with java and as already stated we are already used to how to use and what it will produce for us.

http://www.coverity.com/

**Comment by scantwell** [comment]
Might be worth researching that the coverity we have access to includes the static analysis tool. This could be run by going through the steps to test a program from last quarter. In addition if we still have the notes on how to setup coverity from last semester we should save them somewhere.

**Comment by jcrrad** [comment]
http://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#Java
thats a list of other options we can look into if we decide we want to find one that better fits us and our project.

**Comment by scantwell** [comment]
Could not find the actual document, I emailed Micheal Conway to see if he could forward it to me.
In the meantime I stumbled across this link in my browser history. This is the vm request link, I am working on recreating the steps.

VM Request: https://vcl.cci.drexel.edu/vcl/index.php?mode=selectauth

**Comment by scantwell** [comment]
After connection to the CCI Virtual Computing Lab, it seems as though I am restricted to creating a VM. I will have to wait on Mike Conway response. In the meantime I am putting this issue on a hold.

**Comment by scantwell** [comment]
Received an email back from Michael Conway, he stated that we would need to contact Bruce Char or IRT in order to use Drexel's Lisence for Coverity software. I could reach out to IRT in the meantime however he also said that FreeBugs might be a good tool and it is under "The GNU Lesser General Public License (LGPL)" As per a quick inspection it seems like this could do the job. I will be inspecting further.

**Comment by scantwell** [comment]
So FindBugs it is! I have experimented with it and it has a very very simple interface. You can find it in the Eclipse Market place by searching "FindBugs". After install you can right click a project in the "Package Explorer", find the item "FindBugs" and click "FindBugs." This will analyze your code the results can be seen by a number suffixed to the end of your package directory. This number indicates the number of bugs, similarly when package is expanded the numbers next to the file shows how many bugs in each file. I do recommend going into preferences and allowing it to run an analysis every time a class is modified. 

This site highlights what I explained and more.
http://findbugs.sourceforge.net/manual/eclipse.html#d0e1759
