### ISSUE TITLE
Open discussion for code standards

### ISSUE THREAD

**Issue by scantwell** [jcrrad/Chess#9]
Let us define some coding standards. For example, spacing and documentations. We could always use a predefined standard for instance Google, or Microsoft, there might be a tool to help us format each class we create. All said, this will be an open discussion post for evolving some standards.

**Comment by scantwell** [comment]
I think it is relevant to add the tools here as well.

Static Analysis Tool: FindBugs http://findbugs.sourceforge.net/
Documentation: JAutodocs http://jautodoc.sourceforge.net/index.html#usage
Unit Testing: JUnit

**Comment by Brisbin** [comment]
Unit Testing: MoreUnit - it's an additional tool to JUnit that assists in writing tests - http://moreunit.sourceforge.net/
Code Coverage: EclEmma - http://www.eclemma.org/
